url: https://jsonplaceholder.typicode.com
endpoints:
  - endpoint: /posts
    method: GET
    body: null
  - endpoint: /comments
    method: GET
    body: null
  - endpoint: /todos
    method: GET
    body: null
  - endpoint: /posts
    method: POST
    body: '{"title": "foo", "body": "bar", "userId": 1}'

timeout: 1000 # ms
